import type { Metadata } from "next";
import { Roboto, Lato } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/src/providers/AppProviders";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${roboto.variable} ${lato.variable} antialiased bg-white`}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
